swagger: '2.0'
info:
  version: 1.0.0
  title: WantIt API documents.
  description: Server side code for WantIt.
  termsOfService: http://example.com/terms/
  contact:
    name: Toshimitsu Kugimoto
    url: null
    email: null
  license:
    name: Toshimitsu Kugimoto
    url: null
paths:
  '/user':
    post:
      description: Fetch User Info
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              display-name:
                type: string
              post_ids:
                type: array
                items:
                  type: number
              created_at:
                type: date
  '/users':
    post:
      description: Fetch User Info
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              display-name:
                type: string
              post_ids:
                type: array
                items:
                  type: number
              created_at:
                type: date
